FROM python:3.11-slim as builder

WORKDIR /app

RUN pip install --no-cache-dir fastapi[all] uvicorn[standard]

COPY . .

EXPOSE 80

CMD ["uvicorn","main:app","--reload","--host","0.0.0.0","--port","80"]
